Add usage for Java
WaseemSabir/BatteryPermissionHelper pull request #13
Opened 2024-11-23 19:15 UTC by Caceresenzo

Java is technically supported but not documented.

Closes #12

2025-01-08 10:20 UTC, WaseemSabir requested changes
good work, just a minor comment.

2025-01-15 10:19 UTC, WaseemSabir submitted a review, later dismissed
looks good.

We can rename `dialog` to `buttonInDialog`, but either way is fine.

2025-01-15 10:42 UTC, Caceresenzo commented
I just did, tell me if you need anything else.

2025-01-15 10:48 UTC, WaseemSabir approved these changes
good job! 
pls merge.

2025-01-15 10:57 UTC, Caceresenzo commented
I don't have the right sorry.

![image](https://github.com/user-attachments/assets/3fe3b8c6-1913-46b2-935f-c471d96a776e)

2025-01-16 06:49 UTC, merged